Update STEMSCRIPT

diff --git a/STEMSCRIPT b/STEMSCRIPT
--- a/STEMSCRIPT
+++ b/STEMSCRIPT
@@ -44,6 +44,7 @@ start(){
 	echo tuning >> /var/log/infosec.log
 	echo FTPanonup >> /var/log/infosec.log
 	echo disable_comp >> /var/log/infosec.log
+	echo disable_ipv6 >> /var/log/infosec.log
 	echo apache >> /var/log/infosec.log
 	echo disable_avahi >> /var/log/infosec.log
 	echo rmhack >> /var/log/infosec.log
@@ -176,13 +177,44 @@ firewall(){
 	clear
 }
 
+disable_ipv6(){
+	
+	### Disable IPV6 ###
+	
+	echo "net.ipv6.conf.all.disable_ipv6 = 1" >> /etc/sysctl.conf
+	echo "net.ipv6.conf.default.disable_ipv6 = 1" >> /etc/sysctl.conf
+	echo "net.ipv6.conf.lo.disable_ipv6 = 1"  >> /etc/sysctl.conf
+	
+	### Reload the configuration ###
+	
+	sysctl -p
+	
+	if [ $? -eq 0 ]; then
+		echo $(date):	echo "[+] Diabled IPV6 and reloaded the configurations!" >> /var/log/infosec.log
+	else
+		echo $(date):	echo "[!] Could not set configurations!" >> /var/log/infosec.log
+	fi
+
+	clear
+}
+
 updates(){
+
+	### Check for shellshock vuln prior to updates / upgrades ###
+	
+	sudo env i='() { :;}; echo Your system is Bash vulnerable' bash -c "echo Bash vulnerability test" >> /var/log/infosec.log
 
 	### Updates, upgrades, autoremove, and autoclean ###
 	
 	apt-get update && apt-get dist-upgrade -y
 	apt-get autoremove
 	apt-get autoclean
+	
+	### Enable automatic security updates ###
+	### Creates the "/etc/apt/apt.conf.d/20auto-upgrades" file ###
+	
+	# sudo apt-get install unattended-upgrades
+	# sudo dpkg-reconfigure -plow unattended-upgrades
 	
 	### Checks for daily updates ###
 	
@@ -193,14 +225,6 @@ updates(){
         sed -i 's/APT::Periodic::Update-Package-Lists "0";/APT::Periodic::Update-Package-Lists "1";/g' /etc/apt/apt.conf.d/10periodic >> /var/log/infosec.log 
 		echo $(date): echo "[+] Daily updates configured"
 	fi
-	
-	### Allow unattended updates ###
-	
-	apt-get install unattended-upgrades -y -qq
-	echo -e "APT::Periodic::Update-Package-Lists \"1\";"           >> /etc/apt/apt.conf.d/10periodic
-	echo -e "APT::Periodic::Download-Upgradeable-Packages \"1\";"  >> /etc/apt/apt.conf.d/10periodic
-	echo -e "APT::Periodic::AutocleanInterval \"7\";"              >> /etc/apt/apt.conf.d/10periodic
-	echo -e "APT::Periodic::Unattended-Upgrade \"1\";"             >> /etc/apt/apt.conf.d/10periodic
 	
 	if [ $? -eq 0 ]; then
 		echo $(date):	echo "[+] Ran through updates, affirmed daily updates, and allowed unattended updates!" >> /var/log/infosec.log
@@ -284,6 +308,9 @@ accounts(){
 	### Locks the root account ###
 	
 	passwd -l root
+	
+	# If you need to re-enable the account...
+	# $ passwd -u root
 
 	### Changes all user passwords to 'Cyb3rP4tr10t5' ###
 
@@ -599,8 +626,13 @@ apache(){
 		echo UserDir disabled root >> /etc/apache2/apache2.conf
 	fi
 	
+	### Secure Shared Memory ###
+	
+	echo "tmpfs     /run/shm    tmpfs     ro,noexec,nosuid        0       0" >> /etc/fstab
+	mount -a
+	
 	if [ $? -eq 0 ]; then
-		echo $(date):	echo "[+] Secured apache2!" >> /var/log/infosec.log
+		echo $(date):	echo "[+] Secured apache2 / Secured shared memory!" >> /var/log/infosec.log
 	else
 		echo $(date):	echo "[!] Could not set configurations!" >> /var/log/infosec.log
 	fi
@@ -703,6 +735,7 @@ evergreen(){
 	tuning           #IGS /
 	FTPanonup	 #IGS /
 	disable_comp     #IGS /
+	disable_ipv6     #IGS /
 	apache		 #IGS /
 	disable_avahi    #IGS /
 	rmhack           #IGS /
