Update STEMSCRIPT

diff --git a/STEMSCRIPT b/STEMSCRIPT
--- a/STEMSCRIPT
+++ b/STEMSCRIPT
@@ -24,6 +24,7 @@ mv infosec.log /var/log/
 echo "Make sure to go through everything outside of the script..."
 echo "Launch when ready."
 read WAIT_FOR_USER
+clear
 
 ssh(){
 
@@ -157,19 +158,6 @@ media(){
 	# Finds and lists media files with the following extensions.
 	# There are two sections as one will list to the user / while one logs it to /var/log/infosec.log
 	
-	find / -name "*.mp3"
-	find / -name "*.mp4" 
-	find / -name "*.gif" 
-	find / -name "*.jpg"
-	find / -name "*.jpeg"
-	find / -name "*.png" 
-	find / -name "*.mov"
-	find / -name "*.wav"
-	find / -name "*.tiff"
- 	find / -name "*.tif"
- 	find / -name "*.wmv"
- 	find / -name "*.avi"
-	
 	find / -name "*.mp3" >> /var/log/infosec.log
 	find / -name "*.mp4" >> /var/log/infosec.log 
 	find / -name "*.gif" >> /var/log/infosec.log 
@@ -252,16 +240,14 @@ crontab(){
 
 	# Checks the scheduled jobs
 	
-	ls -la /etc/cron* >> /var/log/infosec.log		# May want to do this outside of the script.
-	echo "[!] PAUSE*"
-	read WAIT_FOR_USER
+	#ls -la /etc/cron*				# May want to do this outside of the script.
+	#read WAIT_FOR_USER
 	
 	# Lists the users crontab
 	
 	crontab -l
 	echo "[!] PAUSE*"
 	read WAIT_FOR_USER
-	clear
 	
 	# Only allow root in cron*
 	#cd /etc/
@@ -411,14 +397,32 @@ apache(){
 	clear
 }
 
+audit(){
+
+	# Updates the audit policy
+	
+	apt-get install auditd
+	
+	if [ $? -eq 0 ]; then
+		echo $(date):	echo "[+] Audit policy updated!"
+	else
+		echo $(date):	echo "[!] Could not set configurations!" >> /var/log/infosec.log
+	fi
+	
+	echo "[!] PAUSE*"
+	read WAIT_FOR_USER
+	clear
+}
+
 # Calling the functions after user has 'approved script for launch'.
 
 	firewall 	 #IGS /					{IGS = In_Good_Standing}
 	ssh			 #IGS /					{NIGS = Not_In_Good_Standing}
 	policy 		 #IGS /
-	media  		 #IGS /
+	audit        #IGS /
+	#media		 #IGS /
 	accounts 	 #IGS / 
-	crontab 	 #IGS / Research
+	#crontab 	 #IGS / Research
 	backdoors 	 #IGS /
 	#hosts 		 #NIGS / Research
 	syncookies 	 #IGS /
