Update STEMSCRIPT

diff --git a/STEMSCRIPT b/STEMSCRIPT
--- a/STEMSCRIPT
+++ b/STEMSCRIPT
@@ -33,7 +33,9 @@ echo services >> /var/log/infosec.log
 echo cron >> /var/log/infosec.log
 echo backdoors >> /var/log/infosec.log
 echo syncookies >> /var/log/infosec.log
+echo tuning >> /var/log/infosec.log
 echo FTPanonup >> /var/log/infosec.log
+echo disable_comp >> /var/log/infosec.log
 echo apache >> /var/log/infosec.log
 echo rmhack1 >> /var/log/infosec.log
 echo rmhack2 >> /var/log/infosec.log
@@ -105,6 +107,10 @@ firewall(){
 	
 	ufw enable
 	ufw default deny
+	
+	### This will allow only 6 connections every 30 seconds from the same IP addr ###
+	
+	ufw limit OpenSSH
 	
 	### Allows the ports (80,443) ###
 	
@@ -397,6 +403,85 @@ syncookies(){
 	clear
 }
 
+tuning(){
+
+	### Kernel Tuning ###
+
+	sysctl kernel.randomize_va_space=1
+    
+        ### Enable IP spoofing protection ###
+        
+        sysctl net.ipv4.conf.all.rp_filter=1
+
+        ### Disable IP source routing ###
+        
+        sysctl net.ipv4.conf.all.accept_source_route=0
+    
+        ### Ignoring broadcasts request ###
+        
+        sysctl net.ipv4.icmp_echo_ignore_broadcasts=1
+        
+        ### Make sure spoofed packets get logged ###
+        
+        sysctl net.ipv4.conf.all.log_martians=1
+        sysctl net.ipv4.conf.default.log_martians=1
+
+        ### Disable ICMP routing redirects ###
+        
+        sysctl -w net.ipv4.conf.all.accept_redirects=0
+        sysctl -w net.ipv6.conf.all.accept_redirects=0
+        sysctl -w net.ipv4.conf.all.send_redirects=0
+
+        ### Disables the magic-sysrq key ###
+        
+        sysctl kernel.sysrq=0
+    
+        ### Turn off the tcp_timestamps ###
+        
+        sysctl net.ipv4.tcp_timestamps=0
+
+        ### Enable bad error message Protection ###
+        
+        sysctl net.ipv4.icmp_ignore_bogus_error_responses=1
+    
+        ### RELOAD WITH NEW SETTINGS ###
+        sysctl -p
+	
+	if [ $? -eq 0 ]; then
+		echo $(date):	echo "[+] Kernel tuning configurations are set and reloaded!" >> /var/log/infosec.log
+	else
+		echo $(date):	echo "[!] Could not set configurations!" >> /var/log/infosec.log
+	fi
+	
+	clear
+}
+
+disable_comp(){
+	
+	### Disables multiple compilers ###
+
+        chmod 000 /usr/bin/byacc
+        chmod 000 /usr/bin/yacc
+        chmod 000 /usr/bin/bcc
+        chmod 000 /usr/bin/kgcc
+        chmod 000 /usr/bin/cc
+        chmod 000 /usr/bin/gcc
+        chmod 000 /usr/bin/*c++
+        chmod 000 /usr/bin/*g++
+        
+        # 755 to bring them back online
+        # It is better to restrict access to them
+        # unless you are working with a specific one
+        
+        if [ $? -eq 0 ]; then
+		echo $(date):	echo "[+] Disabled compilers that are present!" >> /var/log/infosec.log
+	else
+		echo $(date):	echo "[!] Could not set configurations!" >> /var/log/infosec.log
+	fi
+	
+	clear
+}
+
 FTPanonup(){
 	
 	### Copies the contents of the 'ftpusers' file to /var/log/infosec4.log ###
@@ -487,7 +572,9 @@ pass(){
 	cron	 	 #IGS /
 	backdoors 	 #IGS /
 	syncookies       #IGS /
+	tuning           #IGS /
 	FTPanonup	 #IGS /
+	disable_comp     #IGS /
 	apache		 #IGS /
 	rmhack1          #IGS /
 	rmhack2          #IGS /
